
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int ELSE = 30;
  public static final int SEMICOLON = 2;
  public static final int RPAREN = 10;
  public static final int INT = 13;
  public static final int EQUAL = 21;
  public static final int WHILE = 26;
  public static final int NOTEQUAL = 20;
  public static final int MULTI = 18;
  public static final int MAINCLASS = 3;
  public static final int IF = 27;
  public static final int LPAREN = 9;
  public static final int ID = 31;
  public static final int PUBLIC = 4;
  public static final int NUM = 32;
  public static final int STATIC = 5;
  public static final int GREAT = 22;
  public static final int COMMA = 8;
  public static final int FLOAT = 14;
  public static final int EOF = 0;
  public static final int LESSQ = 24;
  public static final int RCBRA = 12;
  public static final int MAIN = 7;
  public static final int DIV = 19;
  public static final int ADD = 16;
  public static final int MINUS = 17;
  public static final int PRINT = 29;
  public static final int error = 1;
  public static final int GREATQ = 25;
  public static final int ASSIGN = 15;
  public static final int FOR = 28;
  public static final int LCBRA = 11;
  public static final int VOID = 6;
  public static final int LESS = 23;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "SEMICOLON",
  "MAINCLASS",
  "PUBLIC",
  "STATIC",
  "VOID",
  "MAIN",
  "COMMA",
  "LPAREN",
  "RPAREN",
  "LCBRA",
  "RCBRA",
  "INT",
  "FLOAT",
  "ASSIGN",
  "ADD",
  "MINUS",
  "MULTI",
  "DIV",
  "NOTEQUAL",
  "EQUAL",
  "GREAT",
  "LESS",
  "LESSQ",
  "GREATQ",
  "WHILE",
  "IF",
  "FOR",
  "PRINT",
  "ELSE",
  "ID",
  "NUM"
  };
}

